irc:
  hostname: bouncer.something.com
  port: 6667
  password: IRCBot:supersecurepassword
  channel: #mysuperawesomeserver
actions:
  join: true
  leave: true
  chat: true
  kick: true
  muted: true
