irc:
  nickname: IRCCraft
  hostname: irc.esper.net
  port: 6667
  password: ""
  channel: "#mysuperawesomeserver"
  chanserv-invite: false
  nickserv-password: ''
actions:
  join: true
  leave: true
  chat: true
  kick: true
  muted: true
  signs: false
  antiadvertiser: false
  unknownchat: false
commands:
  modreq: "{player} submitted a ModReq: {cmd}"
irc-users:
  DeprecatedNether:
    ident: nether
    hostname: deprecatednether.pw
    permission-level: 2
debug: false
