irc:
  nickname: IRCCraft
  hostname: bouncer.something.com
  port: 6667
  password: IRCBot:supersecurepassword
  channel: #mysuperawesomeserver
  chanserv-invite: false
actions:
  join: true
  leave: true
  chat: true
  kick: true
  muted: true
commands:
  modreq: "A ModReq has been submitted!"
