irc:
  nickname: IRCCraft
  hostname: bouncer.something.com
  port: 6667
  password: IRCBot:supersecurepassword
  channel: "#mysuperawesomeserver"
  chanserv-invite: false
actions:
  join: true
  leave: true
  chat: true
  kick: true
  muted: true
  signs: false
  antiadvertiser: false
  unknownchat: false
commands:
  modreq: "{player} submitted a ModReq: {cmd}"
